# Credit to Aran https://medium.com/@AranT/auto-tagging-and-using-semantic-versioning-with-github-actions-e40188d12cf4
name: Bump version
concurrency: production
on:
  push:
    branches:
      - main

permissions:
      id-token: write   # needed to call Github API to use OIDC for AWS auth
      contents: write   # default - needed to write tag to repo
env:
  AWS_ACCOUNT_ID: 747843067444
  AWS_REGION: ap-southeast-2
  AWS_ROLE_NAME: github_actions_in_beemitpoc_jazz_repo
  ROLE_SESSION_NAME: GithubActionsInBeemitpocJazzRepo
  ROLE_DURATION_SECONDS: 900 # aws minimum = 15 mins
  DOCKER_SRC_DIR: .
  ECR_REPOSITORY: beemit-dev-nyanginxjazz

jobs:
  build-nyanginx-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'

    - name: Minor version for each merge
      id: taggerDryRun
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-duration-seconds: ${{ env.ROLE_DURATION_SECONDS }}
        role-session-name: ${{ env.ROLE_SESSION_NAME }}
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.taggerDryRun.outputs.new_tag}} ${{ env.DOCKER_SRC_DIR }}
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.taggerDryRun.outputs.new_tag }}

    # Tests go here

    # Source + doc https://github.com/anothrNick/github-tag-action
    - name: Bump version and push tag
      id: taggerFinal
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
